services:
    nti.mailer:
        class: NTI\EmailBundle\Service\Mailer
        arguments: ["@service_container", "@templating"]
    nti.form.smtptype:
        class: NTI\EmailBundle\Form\SmtpType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

