services:
#    nti_email.example:
#        class: NTI\EmailBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     nti.mailer:
          class: NTI\EmailBundle\Service\Mailer
          arguments: ["@service_container", "@templating"]
